export const SURAHS = [
  { id: 1, arabicName: "الفاتحة", englishName: "Al-Fatihah", urduName: "الفاتحہ", type: "Meccan", verses: 7, juz: 1, manzil: 1 },
  { id: 2, arabicName: "البقرة", englishName: "Al-Baqarah", urduName: "البقرہ", type: "Medinan", verses: 286, juz: 1, manzil: 1 },
  { id: 3, arabicName: "آل عمران", englishName: "Ali 'Imran", urduName: "آل عمران", type: "Medinan", verses: 200, juz: 3, manzil: 1 },
  { id: 4, arabicName: "النساء", englishName: "An-Nisa", urduName: "النساء", type: "Medinan", verses: 176, juz: 4, manzil: 2 },
  { id: 5, arabicName: "المائدة", englishName: "Al-Ma'idah", urduName: "المائدہ", type: "Medinan", verses: 120, juz: 6, manzil: 2 },
  { id: 6, arabicName: "الأنعام", englishName: "Al-An'am", urduName: "الانعام", type: "Meccan", verses: 165, juz: 7, manzil: 2 },
  { id: 7, arabicName: "الأعراف", englishName: "Al-A'raf", urduName: "الاعراف", type: "Meccan", verses: 206, juz: 8, manzil: 2 },
  { id: 8, arabicName: "الأنفال", englishName: "Al-Anfal", urduName: "الانفال", type: "Medinan", verses: 75, juz: 9, manzil: 2 },
  { id: 9, arabicName: "التوبة", englishName: "At-Tawbah", urduName: "التوبہ", type: "Medinan", verses: 129, juz: 10, manzil: 2 },
  { id: 10, arabicName: "يونس", englishName: "Yunus", urduName: "یونس", type: "Meccan", verses: 109, juz: 11, manzil: 3 },
  { id: 11, arabicName: "هود", englishName: "Hud", urduName: "ہود", type: "Meccan", verses: 123, juz: 11, manzil: 3 },
  { id: 12, arabicName: "يوسف", englishName: "Yusuf", urduName: "یوسف", type: "Meccan", verses: 111, juz: 12, manzil: 3 },
  { id: 13, arabicName: "الرعد", englishName: "Ar-Ra'd", urduName: "الرعد", type: "Medinan", verses: 43, juz: 13, manzil: 3 },
  { id: 14, arabicName: "إبراهيم", englishName: "Ibrahim", urduName: "ابراہیم", type: "Meccan", verses: 52, juz: 13, manzil: 3 },
  { id: 15, arabicName: "الحجر", englishName: "Al-Hijr", urduName: "الحجر", type: "Meccan", verses: 99, juz: 14, manzil: 3 },
  { id: 16, arabicName: "النحل", englishName: "An-Nahl", urduName: "النحل", type: "Meccan", verses: 128, juz: 14, manzil: 3 },
  { id: 17, arabicName: "الإسراء", englishName: "Al-Isra", urduName: "الاسراء", type: "Meccan", verses: 111, juz: 15, manzil: 3 },
  { id: 18, arabicName: "الكهف", englishName: "Al-Kahf", urduName: "الکہف", type: "Meccan", verses: 110, juz: 15, manzil: 3 },
  { id: 19, arabicName: "مريم", englishName: "Maryam", urduName: "مریم", type: "Meccan", verses: 98, juz: 16, manzil: 4 },
  { id: 20, arabicName: "طه", englishName: "Ta-Ha", urduName: "طہ", type: "Meccan", verses: 135, juz: 16, manzil: 4 },
  { id: 21, arabicName: "الأنبياء", englishName: "Al-Anbiya", urduName: "الانبیاء", type: "Meccan", verses: 112, juz: 17, manzil: 4 },
  { id: 22, arabicName: "الحج", englishName: "Al-Hajj", urduName: "الحج", type: "Medinan", verses: 78, juz: 17, manzil: 4 },
  { id: 23, arabicName: "المؤمنون", englishName: "Al-Mu'minun", urduName: "المومنون", type: "Meccan", verses: 118, juz: 18, manzil: 4 },
  { id: 24, arabicName: "النور", englishName: "An-Nur", urduName: "النور", type: "Medinan", verses: 64, juz: 18, manzil: 4 },
  { id: 25, arabicName: "الفرقان", englishName: "Al-Furqan", urduName: "الفرقان", type: "Meccan", verses: 77, juz: 18, manzil: 4 },
  { id: 26, arabicName: "الشعراء", englishName: "Ash-Shu'ara", urduName: "الشعراء", type: "Meccan", verses: 227, juz: 19, manzil: 4 },
  { id: 27, arabicName: "النمل", englishName: "An-Naml", urduName: "النمل", type: "Meccan", verses: 93, juz: 19, manzil: 4 },
  { id: 28, arabicName: "القصص", englishName: "Al-Qasas", urduName: "القصص", type: "Meccan", verses: 88, juz: 20, manzil: 4 },
  { id: 29, arabicName: "العنكبوت", englishName: "Al-'Ankabut", urduName: "العنکبوت", type: "Meccan", verses: 69, juz: 20, manzil: 5 },
  { id: 30, arabicName: "الروم", englishName: "Ar-Rum", urduName: "الروم", type: "Meccan", verses: 60, juz: 21, manzil: 5 },
  { id: 31, arabicName: "لقمان", englishName: "Luqman", urduName: "لقمان", type: "Meccan", verses: 34, juz: 21, manzil: 5 },
  { id: 32, arabicName: "السجدة", englishName: "As-Sajdah", urduName: "السجدہ", type: "Meccan", verses: 30, juz: 21, manzil: 5 },
  { id: 33, arabicName: "الأحزاب", englishName: "Al-Ahzab", urduName: "الاحزاب", type: "Medinan", verses: 73, juz: 21, manzil: 5 },
  { id: 34, arabicName: "سبأ", englishName: "Saba", urduName: "سبا", type: "Meccan", verses: 54, juz: 22, manzil: 5 },
  { id: 35, arabicName: "فاطر", englishName: "Fatir", urduName: "فاطر", type: "Meccan", verses: 45, juz: 22, manzil: 5 },
  { id: 36, arabicName: "يس", englishName: "Ya-Sin", urduName: "یاسین", type: "Meccan", verses: 83, juz: 22, manzil: 5 },
  { id: 37, arabicName: "الصافات", englishName: "As-Saffat", urduName: "الصافات", type: "Meccan", verses: 182, juz: 23, manzil: 5 },
  { id: 38, arabicName: "ص", englishName: "Sad", urduName: "صاد", type: "Meccan", verses: 88, juz: 23, manzil: 5 },
  { id: 39, arabicName: "الزمر", englishName: "Az-Zumar", urduName: "الزمر", type: "Meccan", verses: 75, juz: 23, manzil: 5 },
  { id: 40, arabicName: "غافر", englishName: "Ghafir", urduName: "غافر", type: "Meccan", verses: 85, juz: 24, manzil: 6 },
  { id: 41, arabicName: "فصلت", englishName: "Fussilat", urduName: "فصلت", type: "Meccan", verses: 54, juz: 24, manzil: 6 },
  { id: 42, arabicName: "الشورى", englishName: "Ash-Shura", urduName: "الشوری", type: "Meccan", verses: 53, juz: 25, manzil: 6 },
  { id: 43, arabicName: "الزخرف", englishName: "Az-Zukhruf", urduName: "الزخرف", type: "Meccan", verses: 89, juz: 25, manzil: 6 },
  { id: 44, arabicName: "الدخان", englishName: "Ad-Dukhan", urduName: "الدخان", type: "Meccan", verses: 59, juz: 25, manzil: 6 },
  { id: 45, arabicName: "الجاثية", englishName: "Al-Jathiyah", urduName: "الجاثیہ", type: "Meccan", verses: 37, juz: 25, manzil: 6 },
  { id: 46, arabicName: "الأحقاف", englishName: "Al-Ahqaf", urduName: "الاحقاف", type: "Meccan", verses: 35, juz: 26, manzil: 6 },
  { id: 47, arabicName: "محمد", englishName: "Muhammad", urduName: "محمد", type: "Medinan", verses: 38, juz: 26, manzil: 6 },
  { id: 48, arabicName: "الفتح", englishName: "Al-Fath", urduName: "الفتح", type: "Medinan", verses: 29, juz: 26, manzil: 6 },
  { id: 49, arabicName: "الحجرات", englishName: "Al-Hujurat", urduName: "الحجرات", type: "Medinan", verses: 18, juz: 26, manzil: 6 },
  { id: 50, arabicName: "ق", englishName: "Qaf", urduName: "قاف", type: "Meccan", verses: 45, juz: 26, manzil: 6 },
  { id: 51, arabicName: "الذاريات", englishName: "Adh-Dhariyat", urduName: "الذاریات", type: "Meccan", verses: 60, juz: 26, manzil: 6 },
  { id: 52, arabicName: "الطور", englishName: "At-Tur", urduName: "الطور", type: "Meccan", verses: 49, juz: 27, manzil: 6 },
  { id: 53, arabicName: "النجم", englishName: "An-Najm", urduName: "النجم", type: "Meccan", verses: 62, juz: 27, manzil: 6 },
  { id: 54, arabicName: "القمر", englishName: "Al-Qamar", urduName: "القمر", type: "Meccan", verses: 55, juz: 27, manzil: 6 },
  { id: 55, arabicName: "الرحمن", englishName: "Ar-Rahman", urduName: "الرحمن", type: "Medinan", verses: 78, juz: 27, manzil: 6 },
  { id: 56, arabicName: "الواقعة", englishName: "Al-Waqi'ah", urduName: "الواقعہ", type: "Meccan", verses: 96, juz: 27, manzil: 7 },
  { id: 57, arabicName: "الحديد", englishName: "Al-Hadid", urduName: "الحدید", type: "Medinan", verses: 29, juz: 27, manzil: 7 },
  { id: 58, arabicName: "المجادلة", englishName: "Al-Mujadila", urduName: "المجادلہ", type: "Medinan", verses: 22, juz: 28, manzil: 7 },
  { id: 59, arabicName: "الحشر", englishName: "Al-Hashr", urduName: "الحشر", type: "Medinan", verses: 24, juz: 28, manzil: 7 },
  { id: 60, arabicName: "الممتحنة", englishName: "Al-Mumtahanah", urduName: "الممتحنہ", type: "Medinan", verses: 13, juz: 28, manzil: 7 },
  { id: 61, arabicName: "الصف", englishName: "As-Saf", urduName: "الصف", type: "Medinan", verses: 14, juz: 28, manzil: 7 },
  { id: 62, arabicName: "الجمعة", englishName: "Al-Jumu'ah", urduName: "الجمعہ", type: "Medinan", verses: 11, juz: 28, manzil: 7 },
  { id: 63, arabicName: "المنافقون", englishName: "Al-Munafiqun", urduName: "المنافقون", type: "Medinan", verses: 11, juz: 28, manzil: 7 },
  { id: 64, arabicName: "التغابن", englishName: "At-Taghabun", urduName: "التغابن", type: "Medinan", verses: 18, juz: 28, manzil: 7 },
  { id: 65, arabicName: "الطلاق", englishName: "At-Talaq", urduName: "الطلاق", type: "Medinan", verses: 12, juz: 28, manzil: 7 },
  { id: 66, arabicName: "التحريم", englishName: "At-Tahrim", urduName: "التحریم", type: "Medinan", verses: 12, juz: 28, manzil: 7 },
  { id: 67, arabicName: "الملك", englishName: "Al-Mulk", urduName: "الملک", type: "Meccan", verses: 30, juz: 29, manzil: 7 },
  { id: 68, arabicName: "القلم", englishName: "Al-Qalam", urduName: "القلم", type: "Meccan", verses: 52, juz: 29, manzil: 7 },
  { id: 69, arabicName: "الحاقة", englishName: "Al-Haqqah", urduName: "الحاقہ", type: "Meccan", verses: 52, juz: 29, manzil: 7 },
  { id: 70, arabicName: "المعارج", englishName: "Al-Ma'arij", urduName: "المعارج", type: "Meccan", verses: 44, juz: 29, manzil: 7 },
  { id: 71, arabicName: "نوح", englishName: "Nuh", urduName: "نوح", type: "Meccan", verses: 28, juz: 29, manzil: 7 },
  { id: 72, arabicName: "الجن", englishName: "Al-Jinn", urduName: "الجن", type: "Meccan", verses: 28, juz: 29, manzil: 7 },
  { id: 73, arabicName: "المزمل", englishName: "Al-Muzzammil", urduName: "المزمل", type: "Meccan", verses: 20, juz: 29, manzil: 7 },
  { id: 74, arabicName: "المدثر", englishName: "Al-Muddaththir", urduName: "المدثر", type: "Meccan", verses: 56, juz: 29, manzil: 7 },
  { id: 75, arabicName: "القيامة", englishName: "Al-Qiyamah", urduName: "القیامۃ", type: "Meccan", verses: 40, juz: 29, manzil: 7 },
  { id: 76, arabicName: "الإنسان", englishName: "Al-Insan", urduName: "الانسان", type: "Medinan", verses: 31, juz: 29, manzil: 7 },
  { id: 77, arabicName: "المرسلات", englishName: "Al-Mursalat", urduName: "المرسلات", type: "Meccan", verses: 50, juz: 29, manzil: 7 },
  { id: 78, arabicName: "النبأ", englishName: "An-Naba", urduName: "النبأ", type: "Meccan", verses: 40, juz: 30, manzil: 7 },
  { id: 79, arabicName: "النازعات", englishName: "An-Nazi'at", urduName: "النازعات", type: "Meccan", verses: 46, juz: 30, manzil: 7 },
  { id: 80, arabicName: "عبس", englishName: "'Abasa", urduName: "عبس", type: "Meccan", verses: 42, juz: 30, manzil: 7 },
  { id: 81, arabicName: "التكوير", englishName: "At-Takwir", urduName: "التکویر", type: "Meccan", verses: 29, juz: 30, manzil: 7 },
  { id: 82, arabicName: "الانفطار", englishName: "Al-Infitar", urduName: "الانفطار", type: "Meccan", verses: 19, juz: 30, manzil: 7 },
  { id: 83, arabicName: "المطففين", englishName: "Al-Mutaffifin", urduName: "المطففین", type: "Meccan", verses: 36, juz: 30, manzil: 7 },
  { id: 84, arabicName: "الانشقاق", englishName: "Al-Inshiqaq", urduName: "الانشقاق", type: "Meccan", verses: 25, juz: 30, manzil: 7 },
  { id: 85, arabicName: "البروج", englishName: "Al-Buruj", urduName: "البروج", type: "Meccan", verses: 22, juz: 30, manzil: 7 },
  { id: 86, arabicName: "الطارق", englishName: "At-Tariq", urduName: "الطارق", type: "Meccan", verses: 17, juz: 30, manzil: 7 },
  { id: 87, arabicName: "الأعلى", englishName: "Al-A'la", urduName: "الاعلیٰ", type: "Meccan", verses: 19, juz: 30, manzil: 7 },
  { id: 88, arabicName: "الغاشية", englishName: "Al-Ghashiyah", urduName: "الغاشیہ", type: "Meccan", verses: 26, juz: 30, manzil: 7 },
  { id: 89, arabicName: "الفجر", englishName: "Al-Fajr", urduName: "الفجر", type: "Meccan", verses: 30, juz: 30, manzil: 7 },
  { id: 90, arabicName: "البلد", englishName: "Al-Balad", urduName: "البلد", type: "Meccan", verses: 20, juz: 30, manzil: 7 },
  { id: 91, arabicName: "الشمس", englishName: "Ash-Shams", urduName: "الشمس", type: "Meccan", verses: 15, juz: 30, manzil: 7 },
  { id: 92, arabicName: "الليل", englishName: "Al-Layl", urduName: "اللیل", type: "Meccan", verses: 21, juz: 30, manzil: 7 },
  { id: 93, arabicName: "الضحى", englishName: "Ad-Duha", urduName: "الضحیٰ", type: "Meccan", verses: 11, juz: 30, manzil: 7 },
  { id: 94, arabicName: "الشرح", englishName: "Ash-Sharh", urduName: "الشرح", type: "Meccan", verses: 8, juz: 30, manzil: 7 },
  { id: 95, arabicName: "التين", englishName: "At-Tin", urduName: "التین", type: "Meccan", verses: 8, juz: 30, manzil: 7 },
  { id: 96, arabicName: "العلق", englishName: "Al-'Alaq", urduName: "العلق", type: "Meccan", verses: 19, juz: 30, manzil: 7 },
  { id: 97, arabicName: "القدر", englishName: "Al-Qadr", urduName: "القدر", type: "Meccan", verses: 5, juz: 30, manzil: 7 },
  { id: 98, arabicName: "البينة", englishName: "Al-Bayyinah", urduName: "البینۃ", type: "Medinan", verses: 8, juz: 30, manzil: 7 },
  { id: 99, arabicName: "الزلزلة", englishName: "Az-Zalzalah", urduName: "الزلزلہ", type: "Medinan", verses: 8, juz: 30, manzil: 7 },
  { id: 100, arabicName: "العاديات", englishName: "Al-'Adiyat", urduName: "العادیات", type: "Meccan", verses: 11, juz: 30, manzil: 7 },
  { id: 101, arabicName: "القارعة", englishName: "Al-Qari'ah", urduName: "القارعہ", type: "Meccan", verses: 11, juz: 30, manzil: 7 },
  { id: 102, arabicName: "التكاثر", englishName: "At-Takathur", urduName: "التکاثر", type: "Meccan", verses: 8, juz: 30, manzil: 7 },
  { id: 103, arabicName: "العصر", englishName: "Al-'Asr", urduName: "العصر", type: "Meccan", verses: 3, juz: 30, manzil: 7 },
  { id: 104, arabicName: "الهمزة", englishName: "Al-Humazah", urduName: "الہمزہ", type: "Meccan", verses: 9, juz: 30, manzil: 7 },
  { id: 105, arabicName: "الفيل", englishName: "Al-Fil", urduName: "الفیل", type: "Meccan", verses: 5, juz: 30, manzil: 7 },
  { id: 106, arabicName: "قريش", englishName: "Quraysh", urduName: "قریش", type: "Meccan", verses: 4, juz: 30, manzil: 7 },
  { id: 107, arabicName: "الماعون", englishName: "Al-Ma'un", urduName: "الماعون", type: "Meccan", verses: 7, juz: 30, manzil: 7 },
  { id: 108, arabicName: "الكوثر", englishName: "Al-Kawthar", urduName: "الکوثر", type: "Meccan", verses: 3, juz: 30, manzil: 7 },
  { id: 109, arabicName: "الكافرون", englishName: "Al-Kafirun", urduName: "الکافرون", type: "Meccan", verses: 6, juz: 30, manzil: 7 },
  { id: 110, arabicName: "النصر", englishName: "An-Nasr", urduName: "النصر", type: "Medinan", verses: 3, juz: 30, manzil: 7 },
  { id: 111, arabicName: "المسد", englishName: "Al-Masad", urduName: "المسد", type: "Meccan", verses: 5, juz: 30, manzil: 7 },
  { id: 112, arabicName: "الإخلاص", englishName: "Al-Ikhlas", urduName: "الاخلاص", type: "Meccan", verses: 4, juz: 30, manzil: 7 },
  { id: 113, arabicName: "الفلق", englishName: "Al-Falaq", urduName: "الفلق", type: "Meccan", verses: 5, juz: 30, manzil: 7 },
  { id: 114, arabicName: "الناس", englishName: "An-Nas", urduName: "الناس", type: "Meccan", verses: 6, juz: 30, manzil: 7 },
];

export const JUZ_DATA = Array.from({ length: 30 }, (_, i) => {
  const juzNum = i + 1;
  const surahs = SURAHS.filter(s => s.juz === juzNum);
  return {
    id: juzNum,
    surahs: surahs.map(s => s.englishName),
    surahIds: surahs.map(s => s.id),
    totalVerses: surahs.reduce((acc, s) => acc + s.verses, 0),
  };
});

export const MANZIL_DATA = [
  { id: 1, name: "Manzil 1", surahs: "Al-Fatihah – Al-Baqarah (parts)", surahRange: [1, 2], description: "Surahs 1-2 (partial)", estimatedMinutes: 120 },
  { id: 2, name: "Manzil 2", surahs: "Al-Nisa – Al-Anfal (parts)", surahRange: [4, 8], description: "Surahs 4-8 (partial)", estimatedMinutes: 90 },
  { id: 3, name: "Manzil 3", surahs: "Yunus – An-Nahl (parts)", surahRange: [10, 16], description: "Surahs 10-16", estimatedMinutes: 80 },
  { id: 4, name: "Manzil 4", surahs: "Al-Isra – Al-Furqan", surahRange: [17, 25], description: "Surahs 17-25", estimatedMinutes: 70 },
  { id: 5, name: "Manzil 5", surahs: "Ash-Shu'ara – Ya-Sin", surahRange: [26, 36], description: "Surahs 26-36", estimatedMinutes: 65 },
  { id: 6, name: "Manzil 6", surahs: "As-Saffat – Al-Hujurat", surahRange: [37, 49], description: "Surahs 37-49", estimatedMinutes: 60 },
  { id: 7, name: "Manzil 7", surahs: "Qaf – An-Nas", surahRange: [50, 114], description: "Surahs 50-114", estimatedMinutes: 55 },
];

export const TRANSLATION_EDITIONS: Record<string, { code: string; label: string; rtl?: boolean }> = {
  english: { code: "en.sahih", label: "English (Sahih)" },
  urdu: { code: "ur.jalandhry", label: "اردو (جالندھری)", rtl: true },
  french: { code: "fr.hamidullah", label: "Français" },
  german: { code: "de.aburida", label: "Deutsch" },
  spanish: { code: "es.cortes", label: "Español" },
  turkish: { code: "tr.ates", label: "Türkçe" },
  hindi: { code: "hi.hindi", label: "हिन्दी" },
  bengali: { code: "bn.bengali", label: "বাংলা" },
  indonesian: { code: "id.indonesian", label: "Bahasa Indonesia" },
  russian: { code: "ru.kuliev", label: "Русский" },
  chinese: { code: "zh.majian", label: "中文" },
  persian: { code: "fa.makarem", label: "فارسی", rtl: true },
  arabic: { code: "ar.muyassar", label: "العربية (تفسير)", rtl: true },
};

export const RECITERS = [
  { id: "Alafasy_128kbps", name: "Mishary Rashid Alafasy" },
  { id: "Husary_128kbps", name: "Mahmoud Khalil Al-Husary" },
  { id: "Sudais_192kbps", name: "Abdurrahman As-Sudais" },
  { id: "AbdulBaset_Murattal_192kbps", name: "Abdul Basit (Murattal)" },
  { id: "Minshawi_Mujawwad_192kbps", name: "Mohamed Siddiq El-Minshawi" },
];

export interface HadithBook {
  slug: string;
  gadingSlug: string | null;
  fawazBook: string;
  name: string;
  arabicName: string;
  totalHadith: number;
  description: string;
}

export const HADITH_BOOKS: HadithBook[] = [
  { slug: "bukhari", gadingSlug: "bukhari", fawazBook: "bukhari", name: "Sahih Bukhari", arabicName: "صحيح البخاري", totalHadith: 7563, description: "The most authentic hadith collection compiled by Imam Muhammad al-Bukhari" },
  { slug: "muslim", gadingSlug: "muslim", fawazBook: "muslim", name: "Sahih Muslim", arabicName: "صحيح مسلم", totalHadith: 7470, description: "Second most authentic collection by Imam Muslim ibn al-Hajjaj" },
  { slug: "abu-dawud", gadingSlug: "abu-dawud", fawazBook: "abudawud", name: "Sunan Abu Dawood", arabicName: "سنن أبي داود", totalHadith: 5274, description: "Compiled by Imam Abu Dawud, focusing on legal matters" },
  { slug: "tirmidhi", gadingSlug: "tirmidhi", fawazBook: "tirmizi", name: "Jami at-Tirmidhi", arabicName: "جامع الترمذي", totalHadith: 3956, description: "Compiled by Imam at-Tirmidhi with grading commentary" },
  { slug: "nasai", gadingSlug: "nasai", fawazBook: "nasai", name: "Sunan an-Nasa'i", arabicName: "سنن النسائي", totalHadith: 5761, description: "One of the Kutub al-Sittah by Imam an-Nasa'i" },
  { slug: "ibn-majah", gadingSlug: "ibn-majah", fawazBook: "ibnmajah", name: "Sunan Ibn Majah", arabicName: "سنن ابن ماجه", totalHadith: 4341, description: "The sixth canonical hadith collection by Ibn Majah" },
  { slug: "malik", gadingSlug: "malik", fawazBook: "malik", name: "Muwatta Malik", arabicName: "موطأ مالك", totalHadith: 1852, description: "The earliest hadith collection by Imam Malik ibn Anas" },
  { slug: "riyadussalihin", gadingSlug: "riyadussaliheen", fawazBook: "riyadussalihin", name: "Riyad us-Saliheen", arabicName: "رياض الصالحين", totalHadith: 1906, description: "Gardens of the Righteous by Imam Nawawi" },
  { slug: "mishkat", gadingSlug: null, fawazBook: "mishkat", name: "Mishkat al-Masabih", arabicName: "مشكاة المصابيح", totalHadith: 6284, description: "Comprehensive collection by Al-Khatib at-Tabrizi with commentary" },
  { slug: "nawawi40", gadingSlug: null, fawazBook: "nawawi40", name: "40 Hadith Nawawi", arabicName: "الأربعون النووية", totalHadith: 42, description: "The famous 40 hadith compilation by Imam Nawawi covering core Islamic principles" },
];

export const HADITH_LANGUAGES = [
  { code: "english", label: "English", flag: "🇬🇧", fawazLang: "eng" },
  { code: "urdu", label: "اردو", flag: "🇵🇰", fawazLang: "urd", rtl: true },
  { code: "indonesian", label: "Bahasa Indonesia", flag: "🇮🇩", fawazLang: "ind" },
  { code: "arabic", label: "العربية", flag: "🇸🇦", fawazLang: "ara", rtl: true },
  { code: "french", label: "Français", flag: "🇫🇷", fawazLang: "fra" },
  { code: "turkish", label: "Türkçe", flag: "🇹🇷", fawazLang: "tur" },
  { code: "bengali", label: "বাংলা", flag: "🇧🇩", fawazLang: "ben" },
  { code: "chinese", label: "中文", flag: "🇨🇳", fawazLang: "zho" },
];
